# Data Preprocessing

We begin by importing the necessary libraries.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn
import matplotlib.lines as mlines
import statsmodels.api as sm

from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn import datasets
from stargazer.stargazer import Stargazer
from keras.models import Sequential
from keras.layers import Dense
from sklearn.ensemble import RandomForestRegressor

Using TensorFlow backend.

Next we read in the dataset and save it under data.

In [2]:
data = pd.read_csv('peru_for_ml_course.csv')

We set the display option to show all rows and all columns of the dataset.

In [3]:
pd.options.display.max_rows = None
pd.options.display.max_columns = None

We can take a look at the head of the data.

In [4]:
data.head()

,lnpercapitaconsumption,d_fuel_other,d_fuel_wood,d_fuel_coal,d_fuel_kerosene,d_fuel_gas,d_fuel_electric,d_fuel_none,d_water_other,d_water_river,d_water_well,d_water_truck,d_water_pylon,d_water_outside,d_water_inside,d_drain_none,d_drain_river,d_drain_cesspool,d_drain_septic,d_drain_outside,d_drain_inside,d_wall_other,d_wall_woodmat,d_wall_stonemud,d_wall_quincha,d_wall_tapia,d_wall_adobe,d_wall_stonecement,d_wall_brickcement,d_roof_other,d_roof_straw,d_roof_mat,d_roof_platecane,d_roof_tile,d_roof_wood,d_roof_concrete,d_floor_other,d_floor_earth,d_floor_cement,d_floor_wood,d_floor_tile,d_floor_sheets,d_floor_parquet,d_electricity,d_telephone,d_h_educ_none,d_h_educ_pre,d_h_educ_prim,d_h_educ_sec,d_h_educ_higher_nouni,d_h_educ_higher_uni,d_h_educ_post,d_max_educ_none,d_max_educ_prim,d_max_educ_sec,d_max_educ_higher_nouni,d_max_educ_higher_uni,d_insurance_0,d_insurance_1,d_insurance_2,d_insurance_3,d_insurance_4plus,d_crowd_lessthan1,d_crowd_1to2,d_crowd_2to4,d_crowd_4to6,d_crowd_6plus,d_lux_0,d_lux_1,d_lux_2,d_lux_3,d_lux_4,d_lux_5,training,percapitaconsumption,poor,h_hhsize,id_for_matlab,hhid,lncaphat_OLS,percapitahat_OLS
0,NaN,0,1,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,0,0,0,1,0,0,0,0,1.0,0.0,0.0,0.0,0.0,1,0,0,0,0,0,0,NaN,0,1,1,233710511,5.246471,284.4243
1,NaN,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1,0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0,0,1,0,0,0,0,0,1,0,0.0,1.0,0.0,0.0,0.0,0,0,0,1,0,0,0,NaN,0,3,2,295508011,6.129468,522.8840
2,NaN,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1,1,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0,0,0,0,1,0,0,0,0,1,1.0,0.0,0.0,0.0,0.0,0,0,0,1,0,0,0,NaN,0,4,3,257600211,6.665577,878.4961
3,NaN,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1,1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0,0,1,0,0,1,0,0,0,0,0.0,0.0,1.0,0.0,0.0,1,0,0,0,0,0,0,NaN,1,9,4,198104311,6.088295,567.4705
4,NaN,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0,0,1,0,0,0,0,0,0,1,0.0,1.0,0.0,0.0,0.0,1,0,0,0,0,0,0,NaN,1,8,5,24805311,5.008170,115.4929

We can also look at the head of the data with all columns.

In [5]:
display(data.head())

,lnpercapitaconsumption,d_fuel_other,d_fuel_wood,d_fuel_coal,d_fuel_kerosene,d_fuel_gas,d_fuel_electric,d_fuel_none,d_water_other,d_water_river,d_water_well,d_water_truck,d_water_pylon,d_water_outside,d_water_inside,d_drain_none,d_drain_river,d_drain_cesspool,d_drain_septic,d_drain_outside,d_drain_inside,d_wall_other,d_wall_woodmat,d_wall_stonemud,d_wall_quincha,d_wall_tapia,d_wall_adobe,d_wall_stonecement,d_wall_brickcement,d_roof_other,d_roof_straw,d_roof_mat,d_roof_platecane,d_roof_tile,d_roof_wood,d_roof_concrete,d_floor_other,d_floor_earth,d_floor_cement,d_floor_wood,d_floor_tile,d_floor_sheets,d_floor_parquet,d_electricity,d_telephone,d_h_educ_none,d_h_educ_pre,d_h_educ_prim,d_h_educ_sec,d_h_educ_higher_nouni,d_h_educ_higher_uni,d_h_educ_post,d_max_educ_none,d_max_educ_prim,d_max_educ_sec,d_max_educ_higher_nouni,d_max_educ_higher_uni,d_insurance_0,d_insurance_1,d_insurance_2,d_insurance_3,d_insurance_4plus,d_crowd_lessthan1,d_crowd_1to2,d_crowd_2to4,d_crowd_4to6,d_crowd_6plus,d_lux_0,d_lux_1,d_lux_2,d_lux_3,d_lux_4,d_lux_5,training,percapitaconsumption,poor,h_hhsize,id_for_matlab,hhid,lncaphat_OLS,percapitahat_OLS
0,NaN,0,1,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,0,0,0,1,0,0,0,0,1.0,0.0,0.0,0.0,0.0,1,0,0,0,0,0,0,NaN,0,1,1,233710511,5.246471,284.4243
1,NaN,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1,0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0,0,1,0,0,0,0,0,1,0,0.0,1.0,0.0,0.0,0.0,0,0,0,1,0,0,0,NaN,0,3,2,295508011,6.129468,522.8840
2,NaN,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1,1,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0,0,0,0,1,0,0,0,0,1,1.0,0.0,0.0,0.0,0.0,0,0,0,1,0,0,0,NaN,0,4,3,257600211,6.665577,878.4961
3,NaN,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1,1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0,0,1,0,0,1,0,0,0,0,0.0,0.0,1.0,0.0,0.0,1,0,0,0,0,0,0,NaN,1,9,4,198104311,6.088295,567.4705
4,NaN,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0,0,1,0,0,0,0,0,0,1,0.0,1.0,0.0,0.0,0.0,1,0,0,0,0,0,0,NaN,1,8,5,24805311,5.008170,115.4929

We can take a look at the tail of the data.

In [6]:
data.tail()

,lnpercapitaconsumption,d_fuel_other,d_fuel_wood,d_fuel_coal,d_fuel_kerosene,d_fuel_gas,d_fuel_electric,d_fuel_none,d_water_other,d_water_river,d_water_well,d_water_truck,d_water_pylon,d_water_outside,d_water_inside,d_drain_none,d_drain_river,d_drain_cesspool,d_drain_septic,d_drain_outside,d_drain_inside,d_wall_other,d_wall_woodmat,d_wall_stonemud,d_wall_quincha,d_wall_tapia,d_wall_adobe,d_wall_stonecement,d_wall_brickcement,d_roof_other,d_roof_straw,d_roof_mat,d_roof_platecane,d_roof_tile,d_roof_wood,d_roof_concrete,d_floor_other,d_floor_earth,d_floor_cement,d_floor_wood,d_floor_tile,d_floor_sheets,d_floor_parquet,d_electricity,d_telephone,d_h_educ_none,d_h_educ_pre,d_h_educ_prim,d_h_educ_sec,d_h_educ_higher_nouni,d_h_educ_higher_uni,d_h_educ_post,d_max_educ_none,d_max_educ_prim,d_max_educ_sec,d_max_educ_higher_nouni,d_max_educ_higher_uni,d_insurance_0,d_insurance_1,d_insurance_2,d_insurance_3,d_insurance_4plus,d_crowd_lessthan1,d_crowd_1to2,d_crowd_2to4,d_crowd_4to6,d_crowd_6plus,d_lux_0,d_lux_1,d_lux_2,d_lux_3,d_lux_4,d_lux_5,training,percapitaconsumption,poor,h_hhsize,id_for_matlab,hhid,lncaphat_OLS,percapitahat_OLS
46300,6.146313,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1,1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0,0,0,1,0,0,0,0,0,1,0.0,0.0,1.0,0.0,0.0,0,0,0,1,0,0,1,466.9923,0,7,46301,199903811,6.099830,520.8622
46301,5.530832,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1,0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0,0,0,1,0,0,0,0,0,1,0.0,0.0,1.0,0.0,0.0,1,0,0,0,0,0,1,252.3537,0,4,46302,52806611,5.484914,266.1815
46302,5.965293,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1,1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0,0,1,0,0,0,0,0,1,0,0.0,1.0,0.0,0.0,0.0,0,1,0,0,0,0,1,389.6673,0,7,46303,5900111,5.967220,395.6915
46303,4.736676,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1,0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0,0,1,0,0,0,0,0,1,0,1.0,0.0,0.0,0.0,0.0,1,0,0,0,0,0,1,114.0545,1,4,46304,360704611,5.558093,331.6651
46304,7.511497,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1,1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0,0,0,0,1,0,0,1,0,0,1.0,0.0,0.0,0.0,0.0,0,0,0,1,0,0,1,1828.9500,0,3,46305,126110311,6.644368,764.9935

We can take a look at the data types.

In [7]:
data.dtypes

lnpercapitaconsumption     float64
d_fuel_other                 int64
d_fuel_wood                  int64
d_fuel_coal                  int64
d_fuel_kerosene              int64
d_fuel_gas                   int64
d_fuel_electric              int64
d_fuel_none                  int64
d_water_other                int64
d_water_river                int64
d_water_well                 int64
d_water_truck                int64
d_water_pylon                int64
d_water_outside              int64
d_water_inside               int64
d_drain_none                 int64
d_drain_river                int64
d_drain_cesspool             int64
d_drain_septic               int64
d_drain_outside              int64
d_drain_inside               int64
d_wall_other               float64
d_wall_woodmat             float64
d_wall_stonemud            float64
d_wall_quincha             float64
d_wall_tapia               float64
d_wall_adobe               float64
d_wall_stonecement         float64
d_wall_brickcement         float64
d_roof_other               float64
d_roof_straw               float64
d_roof_mat                 float64
d_roof_platecane           float64
d_roof_tile                float64
d_roof_wood                float64
d_roof_concrete            float64
d_floor_other              float64
d_floor_earth              float64
d_floor_cement             float64
d_floor_wood               float64
d_floor_tile               float64
d_floor_sheets             float64
d_floor_parquet            float64
d_electricity                int64
d_telephone                  int64
d_h_educ_none              float64
d_h_educ_pre               float64
d_h_educ_prim              float64
d_h_educ_sec               float64
d_h_educ_higher_nouni      float64
d_h_educ_higher_uni        float64
d_h_educ_post              float64
d_max_educ_none              int64
d_max_educ_prim              int64
d_max_educ_sec               int64
d_max_educ_higher_nouni      int64
d_max_educ_higher_uni        int64
d_insurance_0                int64
d_insurance_1                int64
d_insurance_2                int64
d_insurance_3                int64
d_insurance_4plus            int64
d_crowd_lessthan1          float64
d_crowd_1to2               float64
d_crowd_2to4               float64
d_crowd_4to6               float64
d_crowd_6plus              float64
d_lux_0                      int64
d_lux_1                      int64
d_lux_2                      int64
d_lux_3                      int64
d_lux_4                      int64
d_lux_5                      int64
training                     int64
percapitaconsumption       float64
poor                         int64
h_hhsize                     int64
id_for_matlab                int64
hhid                         int64
lncaphat_OLS               float64
percapitahat_OLS           float64
dtype: object

We get summary statistics on the columns.

In [8]:
data.describe()

,lnpercapitaconsumption,d_fuel_other,d_fuel_wood,d_fuel_coal,d_fuel_kerosene,d_fuel_gas,d_fuel_electric,d_fuel_none,d_water_other,d_water_river,d_water_well,d_water_truck,d_water_pylon,d_water_outside,d_water_inside,d_drain_none,d_drain_river,d_drain_cesspool,d_drain_septic,d_drain_outside,d_drain_inside,d_wall_other,d_wall_woodmat,d_wall_stonemud,d_wall_quincha,d_wall_tapia,d_wall_adobe,d_wall_stonecement,d_wall_brickcement,d_roof_other,d_roof_straw,d_roof_mat,d_roof_platecane,d_roof_tile,d_roof_wood,d_roof_concrete,d_floor_other,d_floor_earth,d_floor_cement,d_floor_wood,d_floor_tile,d_floor_sheets,d_floor_parquet,d_electricity,d_telephone,d_h_educ_none,d_h_educ_pre,d_h_educ_prim,d_h_educ_sec,d_h_educ_higher_nouni,d_h_educ_higher_uni,d_h_educ_post,d_max_educ_none,d_max_educ_prim,d_max_educ_sec,d_max_educ_higher_nouni,d_max_educ_higher_uni,d_insurance_0,d_insurance_1,d_insurance_2,d_insurance_3,d_insurance_4plus,d_crowd_lessthan1,d_crowd_1to2,d_crowd_2to4,d_crowd_4to6,d_crowd_6plus,d_lux_0,d_lux_1,d_lux_2,d_lux_3,d_lux_4,d_lux_5,training,percapitaconsumption,poor,h_hhsize,id_for_matlab,hhid,lncaphat_OLS,percapitahat_OLS
count,23153.000000,46305.000000,46305.000000,46305.000000,46305.000000,46305.000000,46305.000000,46305.000000,46305.000000,46305.000000,46305.000000,46305.000000,46305.000000,46305.000000,46305.000000,46305.000000,46305.000000,46305.000000,46305.000000,46305.000000,46305.000000,45382.000000,45382.000000,45382.000000,45382.000000,45382.000000,45382.000000,45382.000000,45382.000000,45382.000000,45382.000000,45382.000000,45382.000000,45382.000000,45382.000000,45382.000000,45382.000000,45382.000000,45382.000000,45382.000000,45382.000000,45382.000000,45382.000000,46305.000000,46305.000000,46301.000000,46301.000000,46301.000000,46301.000000,46301.000000,46301.000000,46301.000000,46305.000000,46305.000000,46305.000000,46305.000000,46305.000000,46305.000000,46305.000000,46305.000000,46305.000000,46305.000000,45382.000000,45382.000000,45382.000000,45382.000000,45382.000000,46305.000000,46305.000000,46305.000000,46305.000000,46305.000000,46305.000000,46305.000000,23153.000000,46305.000000,46305.000000,46305.000000,4.630500e+04,45378.000000,45378.000000
mean,5.853638,0.104244,0.307202,0.025656,0.004557,0.518734,0.007796,0.031811,0.041421,0.207947,0.040341,0.017320,0.019285,0.064291,0.609394,0.149552,0.021682,0.135730,0.155750,0.059281,0.472692,0.050483,0.113591,0.013067,0.023512,0.100304,0.299348,0.006038,0.393658,0.012009,0.071372,0.013243,0.499714,0.118571,0.013860,0.271231,0.011987,0.394121,0.404323,0.079701,0.057181,0.030364,0.022322,0.837728,0.204557,0.080689,0.000216,0.382411,0.331742,0.103000,0.088249,0.013693,0.032372,0.171234,0.405075,0.169766,0.197041,0.179117,0.163632,0.163784,0.150610,0.342857,0.300119,0.427020,0.205831,0.047882,0.019149,0.544974,0.193845,0.113703,0.067293,0.043797,0.036389,0.500011,459.015591,0.280207,4.012094,23153.000000,1.869936e+08,5.850041,459.121087
std,0.742314,0.305580,0.461339,0.158108,0.067350,0.499654,0.087952,0.175498,0.199264,0.405843,0.196760,0.130462,0.137527,0.245273,0.487891,0.356635,0.145646,0.342506,0.362622,0.236152,0.499259,0.218941,0.317318,0.113562,0.151523,0.300408,0.457977,0.077468,0.488566,0.108928,0.257448,0.114316,0.500005,0.323287,0.116912,0.444600,0.108829,0.488666,0.490766,0.270833,0.232191,0.171590,0.147729,0.368704,0.403382,0.272360,0.014695,0.485981,0.470844,0.303962,0.283659,0.116214,0.176989,0.376718,0.490912,0.375431,0.397768,0.383454,0.369946,0.370083,0.357672,0.474669,0.458315,0.494651,0.404312,0.213520,0.137049,0.497979,0.395313,0.317453,0.250531,0.204644,0.187258,0.500005,401.571900,0.449105,2.093215,13367.246444,1.111905e+08,0.605646,293.660061
min,2.110213,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.250000,0.000000,1.000000,1.000000,1.010110e+05,4.434424,-57.498260
25%,5.344018,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,209.352100,0.000000,2.000000,11577.000000,9.080021e+07,5.332906,235.941375
50%,5.877269,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,356.833300,0.000000,4.000000,23153.000000,1.828055e+08,5.871004,404.708750
75%,6.354380,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,575.005700,1.000000,5.000000,34729.000000,2.814050e+08,6.306364,611.242975
max,8.858051,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,7030.769000,1.000000,20.000000,46305.000000,4.035098e+08,7.738163,2132.654000

We can get some further information on our dataset.

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46305 entries, 0 to 46304
Data columns (total 81 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   lnpercapitaconsumption   23153 non-null  float64
 1   d_fuel_other             46305 non-null  int64
 2   d_fuel_wood              46305 non-null  int64
 3   d_fuel_coal              46305 non-null  int64
 4   d_fuel_kerosene          46305 non-null  int64
 5   d_fuel_gas               46305 non-null  int64
 6   d_fuel_electric          46305 non-null  int64
 7   d_fuel_none              46305 non-null  int64
 8   d_water_other            46305 non-null  int64
 9   d_water_river            46305 non-null  int64
 10  d_water_well             46305 non-null  int64
 11  d_water_truck            46305 non-null  int64
 12  d_water_pylon            46305 non-null  int64
 13  d_water_outside          46305 non-null  int64
 14  d_water_inside           46305 non-null  int64
 15  d_drain_none             46305 non-null  int64
 16  d_drain_river            46305 non-null  int64
 17  d_drain_cesspool         46305 non-null  int64
 18  d_drain_septic           46305 non-null  int64
 19  d_drain_outside          46305 non-null  int64
 20  d_drain_inside           46305 non-null  int64
 21  d_wall_other             45382 non-null  float64
 22  d_wall_woodmat           45382 non-null  float64
 23  d_wall_stonemud          45382 non-null  float64
 24  d_wall_quincha           45382 non-null  float64
 25  d_wall_tapia             45382 non-null  float64
 26  d_wall_adobe             45382 non-null  float64
 27  d_wall_stonecement       45382 non-null  float64
 28  d_wall_brickcement       45382 non-null  float64
 29  d_roof_other             45382 non-null  float64
 30  d_roof_straw             45382 non-null  float64
 31  d_roof_mat               45382 non-null  float64
 32  d_roof_platecane         45382 non-null  float64
 33  d_roof_tile              45382 non-null  float64
 34  d_roof_wood              45382 non-null  float64
 35  d_roof_concrete          45382 non-null  float64
 36  d_floor_other            45382 non-null  float64
 37  d_floor_earth            45382 non-null  float64
 38  d_floor_cement           45382 non-null  float64
 39  d_floor_wood             45382 non-null  float64
 40  d_floor_tile             45382 non-null  float64
 41  d_floor_sheets           45382 non-null  float64
 42  d_floor_parquet          45382 non-null  float64
 43  d_electricity            46305 non-null  int64
 44  d_telephone              46305 non-null  int64
 45  d_h_educ_none            46301 non-null  float64
 46  d_h_educ_pre             46301 non-null  float64
 47  d_h_educ_prim            46301 non-null  float64
 48  d_h_educ_sec             46301 non-null  float64
 49  d_h_educ_higher_nouni    46301 non-null  float64
 50  d_h_educ_higher_uni      46301 non-null  float64
 51  d_h_educ_post            46301 non-null  float64
 52  d_max_educ_none          46305 non-null  int64
 53  d_max_educ_prim          46305 non-null  int64
 54  d_max_educ_sec           46305 non-null  int64
 55  d_max_educ_higher_nouni  46305 non-null  int64
 56  d_max_educ_higher_uni    46305 non-null  int64
 57  d_insurance_0            46305 non-null  int64
 58  d_insurance_1            46305 non-null  int64
 59  d_insurance_2            46305 non-null  int64
 60  d_insurance_3            46305 non-null  int64
 61  d_insurance_4plus        46305 non-null  int64
 62  d_crowd_lessthan1        45382 non-null  float64
 63  d_crowd_1to2             45382 non-null  float64
 64  d_crowd_2to4             45382 non-null  float64
 65  d_crowd_4to6             45382 non-null  float64
 66  d_crowd_6plus            45382 non-null  float64
 67  d_lux_0                  46305 non-null  int64
 68  d_lux_1                  46305 non-null  int64
 69  d_lux_2                  46305 non-null  int64
 70  d_lux_3                  46305 non-null  int64
 71  d_lux_4                  46305 non-null  int64
 72  d_lux_5                  46305 non-null  int64
 73  training                 46305 non-null  int64
 74  percapitaconsumption     23153 non-null  float64
 75  poor                     46305 non-null  int64
 76  h_hhsize                 46305 non-null  int64
 77  id_for_matlab            46305 non-null  int64
 78  hhid                     46305 non-null  int64
 79  lncaphat_OLS             45378 non-null  float64
 80  percapitahat_OLS         45378 non-null  float64
dtypes: float64(38), int64(43)
memory usage: 28.6 MB

We check how many missing values there are for each column.

In [10]:
data.isna().sum()

lnpercapitaconsumption     23152
d_fuel_other                   0
d_fuel_wood                    0
d_fuel_coal                    0
d_fuel_kerosene                0
d_fuel_gas                     0
d_fuel_electric                0
d_fuel_none                    0
d_water_other                  0
d_water_river                  0
d_water_well                   0
d_water_truck                  0
d_water_pylon                  0
d_water_outside                0
d_water_inside                 0
d_drain_none                   0
d_drain_river                  0
d_drain_cesspool               0
d_drain_septic                 0
d_drain_outside                0
d_drain_inside                 0
d_wall_other                 923
d_wall_woodmat               923
d_wall_stonemud              923
d_wall_quincha               923
d_wall_tapia                 923
d_wall_adobe                 923
d_wall_stonecement           923
d_wall_brickcement           923
d_roof_other                 923
d_roof_straw                 923
d_roof_mat                   923
d_roof_platecane             923
d_roof_tile                  923
d_roof_wood                  923
d_roof_concrete              923
d_floor_other                923
d_floor_earth                923
d_floor_cement               923
d_floor_wood                 923
d_floor_tile                 923
d_floor_sheets               923
d_floor_parquet              923
d_electricity                  0
d_telephone                    0
d_h_educ_none                  4
d_h_educ_pre                   4
d_h_educ_prim                  4
d_h_educ_sec                   4
d_h_educ_higher_nouni          4
d_h_educ_higher_uni            4
d_h_educ_post                  4
d_max_educ_none                0
d_max_educ_prim                0
d_max_educ_sec                 0
d_max_educ_higher_nouni        0
d_max_educ_higher_uni          0
d_insurance_0                  0
d_insurance_1                  0
d_insurance_2                  0
d_insurance_3                  0
d_insurance_4plus              0
d_crowd_lessthan1            923
d_crowd_1to2                 923
d_crowd_2to4                 923
d_crowd_4to6                 923
d_crowd_6plus                923
d_lux_0                        0
d_lux_1                        0
d_lux_2                        0
d_lux_3                        0
d_lux_4                        0
d_lux_5                        0
training                       0
percapitaconsumption       23152
poor                           0
h_hhsize                       0
id_for_matlab                  0
hhid                           0
lncaphat_OLS                 927
percapitahat_OLS             927
dtype: int64

We check the shape of our dataset. We see that there are 46'305 rows/observations and 81 columns/variables.

In [11]:
data.shape

(46305, 81)

We can now start with the actual preprocessing steps.

In the paper, the natural log of per capita consumption (lnpercapitaconsumption), is set to be the dependent variable. The explanatory variables used for the model in the paper are the following.

* d_fuel_wood:                  Household uses wood fuel for cooking 
* d_fuel_coal:                  Household uses coal fuel for cooking 
* d_fuel_kerosene:              Household uses kerosene fuel for cooking 
* d_fuel_gas:                   Household uses gas fuel for cooking 
* d_fuel_electric:              Household uses electricity for cooking 
* d_fuel_none:                  Household does not cook 
* d_water_river:                Water source: river
* d_water_well:                Water source: well
* d_water_truck:                Water source: water truck
* d_water_pylon:                Water source: pylon
* d_water_outside:              Water source: public network outside HH 
* d_water_inside:              Water source: public network inside HH 
* d_drain_none:                 Drainage source: none
* d_drain_river:                Drainage source: river
* d_drain_cesspool:            Drainage source: cesspool
* d_drain_septic:               Drainage source: septic tank
* d_drain_outside:              Drainage source: public network outside HH 
* d_drain_inside:               Drainage source: public network inside HH 
* d_wall_woodmat:             Wall type: wood or mat
* d_wall_stonemud:            Wall type: stone or mud
* d_wall_quincha:             Wall type: quincha
* d_wall_tapia:               Wall type: tapia (rammed earth)
* d_wall_adobe:               Wall type: adobe 
* d_wall_stonecement:         Wall type: stone with lime or cement 
* d_wall_brickcement:         Wall type: brick or cement block 
* d_roof_straw:              Roof type: straw
* d_roof_mat:                 Roof type: mat 
* d_roof_platecane:           Roof type: iron or cane 
* d_roof_tile:               Roof type: tile
* d_roof_wood:               Roof type: wood
* d_roof_concrete:            Roof type: concrete 
* d_floor_earth:              Floor type: earth 
* d_floor_cement:             Floor type: cement
* d_floor_wood:               Floor type: wood
* d_floor_tile:               Floor type: tile
* d_floor_sheets:             Floor type: sheet metal
* d_floor_parquet:            Floor type: parquet
* d_electricity:                Household has electricity
* d_telephone:                  Household has telephone 
* d_h_educ_pre:              Highest education of HH head: pre-school 
* d_h_educ_prim:              Highest education of HH head: primary
* d_h_educ_sec:              Highest education of HH head: secondary
* d_h_educ_higher_nouni:      Highest education of HH head: tertiary (non-univ.) 
* d_h_educ_higher_uni:        Highest education of HH head: tertiary (univ.) 
* d_h_educ_post:              Highest education of HH head: post-graduate 
* d_max_educ_none:              Highest education of anyone in HH: none 
* d_max_educ_prim:             Highest education of anyone in HH: primary
* d_max_educ_sec:               Highest education of anyone in HH: secondary
* d_max_educ_higher_nouni:     Highest education of anyone in HH: tertiary (non-univ.) 
* d_max_educ_higher_uni:        Highest education of anyone in HH: tertiary (univ.)
* d_insurance_1:                1 HH member affiliated w/ health insurance 
* d_insurance_2:                2 HH members affiliated w/ health insurance 
* d_insurance_3:                3 HH members affiliated w/ health insurance 
* d_insurance_4plus:            4+ HH members affiliated w/ health insurance 
* d_crowd_1to2:               1-2 household members per room 
* d_crowd_2to4:               2-4 household members per room 
* d_crowd_4to6:               4-6 household members per room 
* d_crowd_6plus:              6+ household members per room 
* d_lux_1:                      1 of 5 luxury goods owned
* d_lux_2:                      2 of 5 luxury goods owned
* d_lux_3:                      3 of 5 luxury goods owned
* d_lux_4:                      4 of 5 luxury goods owned
* d_lux_5:                      5 of 5 luxury goods owned

Therefore we drop the following columns/variables, which we don't need.

In [12]:
data <- data.drop(['percapitaconsumption','d_fuel_other','d_water_other','d_wall_other','d_roof_other','d_floor_other','d_insurance_0','d_crowd_lessthan1','d_lux_0','training','poor','h_hhsize','id_for_matlab','hhid','lncaphat_OLS','percapitahat_OLS'], axis = 1, inplace = True)

TypeError: bad operand type for unary -: 'NoneType'

If we check for the shape of the data now, we still have 46'305 rows/observations, but we are only left with 65 columns/variables.

In [13]:
data.shape

(46305, 65)

Next, we drop all rows/observations with missing values.

In [14]:
data.dropna(axis=0,inplace=True)

If we check for the shape of the data now, we still have 22'674 rows/observations, and 65 columns/variables.

In [15]:
data.shape

(22674, 65)

This is the preprocessed dataset we can work with in our modelling.

In [17]:
data.to_csv(r'data_preprocessed.csv', index = False, header=True)